name: CI & CD
on:
    push:
        tags:
            - v*
jobs:
  Build-and-Publish:
      runs-on: ubuntu-latest
      permissions:
          contents: write
          id-token: write
      steps:
        - uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4
          with:
              version: 10
        - uses: actions/setup-node@v4
          with:
              node-version: 22.13.1
              registry-url: https://registry.npmjs.org
              cache: pnpm
        - name: Install Dependencies
          run: pnpm i --frozen-lockfile
        
        - name: run test
          run: pnpm run test
        - name: run lint
          run: pnpm run lint
