name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 22.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 22.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 22.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test:e2e
This ensures that pnpm is installed before it is used, preventing the error.

Please find a solution for this failing job. Use the logs, job definition, and any referenced files where the failure occurred. Keep your response focused on the solution and include code suggestions when appropriate.
1 reference
The issue in the workflow is due to missing installation of pnpm which needs to be installed before using it. Here's the updated workflow file to address this:

YAML
name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Install Dependencies
        run: pnpm install     
      - name: Run Tests
        run: pnpm test
        working-directory: src/
